# fly.toml app configuration file generated for eventflow on 2025-05-27T10:57:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eventflow'
primary_region = 'gig'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
