version: '3.4'

services:
  eventflow-api:
    image: eventflowapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ConnectionString=Server=172.16.10.22;Database=EventFlow;User Id=EventUser;Password=12345;TrustServerCertificate=True;
    networks:
      - eventflow-network

networks:
  eventflow-network:
    driver: bridge
